[package]
name = "make-nul"
version = "0.0.0"
edition = "2018"

[dependencies]
skylight = { git = "https://github.com/adumbidiot/skylight-rs", features = [ "objbase", "shlobj", "winbase" ] }

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'
panic = 'abort'
